name: test parserYT_bot

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  Unit_test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
        - uses: actions/checkout@v3
        - name: install python
          uses: actions/setup-python@v4
          with:
            python-version: '3.8'
        - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
          - name: Unit tests run
              run: |
                python -m unittest src/test.py